development:
  adapter: postgresql
  encoding: utf8
  database: five_hundred_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: five_hundred_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: five_hundred_production
  pool: 5
  username:
  password:
