development:
  adapter: postgresql
  encoding: utf8
  database: five_hundred_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: travis_ci_test
  username: postgres

production:
  adapter: postgresql
  encoding: utf8
  database: five_hundred_production
  pool: 5
  username:
  password:
