default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: test-mysql_development

test:
  <<: *default
  database: test-mysql_test

production:
  <<: *default
  database: test-mysql_production
  username: test-mysql
  password: <%= ENV['TEST-MYSQL_DATABASE_PASSWORD'] %>