# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f735bc883c81db7791c72edaf75b2f07d5f65766eb42ac49e3b6b2b656e71fd7e6af5f1116f5827b68b77abe3198301cc99fdc8ff04e2b86e3a386a12173226d

test:
  secret_key_base: c3a5c4618d2045963649d371dc242e80e13ec5b81c3f166c0c5ecef19dd603f28c4ca4c75b936538be3c23cbf4f191f19b08beb6a308f4e1aec030db89c9e605

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
